export const FETCH_CHATS = 'FETCH_CHATS';
export const SET_CURRENT_CHAT = 'SET_CURRENT_CHAT';
export const FRIENDS_ONLINE = 'FRIENDS_ONLINE';
export const FRIEND_ONLINE = 'FRIEND_ONLINE';
export const FRIEND_OFFLINE = 'FRIEND_OFFLINE';
export const SET_SOCKET = 'SET_SOCKET';
export const RECEIVED_MESSAGE = 'RECEIVED_MESSAGE';
export const SENDER_TYPING = 'SENDER_TYPING';
export const SET_MSGBOX_ELEMENT_AND_SENDERTYPING_ELEMENT =
	'SET_MSGBOX_ELEMENT_AND_SENDERTYPING_ELEMENT';

export const SET_A_NEW_MESSAGE_SEEN = 'SET_A_NEW_MESSAGE_SEEN';

export const PAGINATE_MESSAGES = 'PAGINATE_MESSAGES';
export const INCREMENT_SCROLL = 'INCREMENT_SCROLL';
export const CREATE_CHAT = 'CREATE_CHAT';
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP';
export const LEAVE_CURRENT_CHAT = 'LEAVE_CURRENT_CHAT';
export const DELETE_CURRENT_CHAT = 'DELETE_CURRENT_CHAT';

export const A_NEW_NOTIFICATION = 'A_NEW_NOTIFICATION';
